#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99
STOP=98

i2c_core="2"
eth0_cores="1"
wifi_core="0"
usb_core="3"
dma_core="0"

############### util functions ###############

to_hex_list() {
	local cores=$1
	local converted=""
	for core in $(echo $cores | awk '{print}')
	do
		local hex="$(gen_hex_mask "$core")"
		converted="$converted $hex"
	done
	echo `echo $converted | sed 's/^ *//'`
}

gen_hex_mask() {
	local cores=$1
	local mask=0
	for core in $(echo $cores | awk '{print}')
	do
		local bit="$((1 << $core))"
		let "mask = mask + bit"
	done
	local hex="$(printf %x "$mask")"
	echo "$hex"
}

############### assign interrupts ###############
set_irq_cores() {
	local mask="$(gen_hex_mask "$2")"
	echo "set mask $mask for irq: $1"
	echo $mask > "/proc/irq/$1/smp_affinity"
}

set_irq_pattern() {
	local name_pattern="$1"
	local cores="$2"
	
	for irq in `grep "$name_pattern" /proc/interrupts | cut -d: -f1 | sed 's, *,,'`
	do
		set_irq_cores $irq "$cores"
	done
}

set_irqs() {
	#dma
	set_irq_pattern dma "$dma_core"

	#eth0
	set_irq_pattern eth0 "$eth0_cores"

	#pcie
	set_irq_pattern pcie "$wifi_core"

	#usb(eth1)
	set_irq_pattern usb "$usb_core"
	
	#i2c
	set_irq_pattern i2c "$i2c_core"
}

start() {
	set_irqs
}
