#!/bin/sh
[ "$ACTION" = add ] || exit

# 遍历所有网口
for NIC in $(ls /sys/class/net/)
do
  # 检查网口是否支持ethtool命令
  if command -v ethtool &> /dev/null && ethtool $NIC &> /dev/null; then
    # 获取网卡型号
    DRIVER=$(ethtool -i $NIC 2>/dev/null | awk '/^driver:/ {print $2}')

    # 如果无法获取驱动程序信息，则跳过该网卡
    if [ -z "$DRIVER" ]; then
      continue
    fi

    # 判断网卡型号是否为igc
    if [[ $DRIVER == "igc" ]]; then
      # 调整rx缓存
      ethtool -G $NIC rx 1024
    fi
  fi
done
