#!/bin/sh
# From QiuSimons

cd /overlay
rm -rf `ls | egrep -v '(upper|.fs_state)'`
cd /overlay/upper
rm -rf `ls | egrep -v '(etc|usr)'`
cd /overlay/upper/usr
rm -rf `ls | egrep -v '(share)'`
cd /overlay/upper/usr/share
rm -rf `ls | egrep -v '(unblockneteasemusic|passwall)'`
cd /overlay/upper/etc
rm -rf `ls | egrep -v '(config|smartdns|ssr|ssrplus|bench.log|shadow|chinadns-ng|openclash|dnsmasq.ssr|dnsmasq.oversea|ssr_ip|china_ssr.txt)'`
sleep 5 && touch /etc/banner && reboot
